apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
        - name: conversao-peso
          image: giancarloh/conversao-peso:v1
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-peso
spec:
  selector:
    app: conversao-peso
  ports:
    - port: 8080
      targetPort: 80
